MODEL 1 ON LINEAR REGRESSION AND SUPPORTED VECTOR REGRESSION CS-19132 CS-19134 CS-19142 

importing libraries

In [10]:
import numpy as np
import pandas as pd
import pickle

Importing Dataset for Model-1

In [3]:
dataset = pd.read_csv('The_Grades_Dataset.csv')
for column in dataset:
    dataset[column]=dataset[column].replace('A+',4.0)
    dataset[column]=dataset[column].replace('A',4.0)
    dataset[column]=dataset[column].replace('A-',3.7)
    dataset[column]=dataset[column].replace('B+',3.3)
    dataset[column]=dataset[column].replace('B',3.0)
    dataset[column]=dataset[column].replace('B-',2.7)
    dataset[column]=dataset[column].replace('C+',2.3)
    dataset[column]=dataset[column].replace('C',2.0)
    dataset[column]=dataset[column].replace('C-',1.7)
    dataset[column]=dataset[column].replace('D+',1.3)
    dataset[column]=dataset[column].replace('D',1.0)
    dataset[column]=dataset[column].replace('D-',0.7)
    dataset[column]=dataset[column].replace('WU',0)
    dataset[column]=dataset[column].replace('W',0)
    dataset[column]=dataset[column].replace('F',0)
    dataset[column]=dataset[column].replace('I',0)

In [4]:
X1 = dataset.iloc[:, 1:12].values
y1 = dataset.iloc[:, -1].values

Encoding dataset for Model 1

In [5]:
print(X1)

[[2.7 1.3 1.7 ... 2.7 1.7 1.7]
 [4.  1.  1.3 ... 1.3 1.  3.3]
 [4.  3.  4.  ... 3.7 3.7 2.7]
 ...
 [3.  4.  3.7 ... 4.  3.  4. ]
 [4.  3.3 1.  ... 2.7 1.7 4. ]
 [2.  1.  1.  ... 2.  1.3 2.7]]


Handling Missing Values for Model 1

In [6]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer.fit(X1[:,1:12])
X1[:,1:12]=imputer.transform(X1[:,1:12])

In [7]:
print(X1)

[[2.7 1.3 1.7 ... 2.7 1.7 1.7]
 [4.  1.  1.3 ... 1.3 1.  3.3]
 [4.  3.  4.  ... 3.7 3.7 2.7]
 ...
 [3.  4.  3.7 ... 4.  3.  4. ]
 [4.  3.3 1.  ... 2.7 1.7 4. ]
 [2.  1.  1.  ... 2.  1.3 2.7]]


Splitting Dataset

In [8]:
from sklearn.model_selection import train_test_split
X1_train,X1_test,y1_train,y1_test=train_test_split(X1,y1,test_size=0.2,random_state=0)
print(X1_train)


[[4.  3.7 3.3 ... 3.7 2.  4. ]
 [4.  3.3 4.  ... 3.7 4.  4. ]
 [1.7 1.3 2.7 ... 3.3 2.3 1.7]
 ...
 [3.7 3.7 4.  ... 3.3 3.3 4. ]
 [4.  4.  4.  ... 3.7 4.  4. ]
 [3.7 2.3 4.  ... 3.  3.7 3.7]]


Training our Model 1 on linear reg

In [11]:
from sklearn.linear_model import LinearRegression
Regressor1=LinearRegression()
Regressor1.fit(X1_train,y1_train)
with open("one_year_pred_model_one.pkl","wb") as file:
    pickle.dump(Regressor1,file)

testing our dataset on linear regression 

In [12]:

y1_pred_linear=Regressor1.predict(X1_test)

In [13]:
from sklearn.metrics import r2_score
r2_score(y1_test,y1_pred_linear)

0.8144924366365484

training our model on SVR

In [14]:
from sklearn.svm import SVR
regressor2=SVR(kernel='linear') 
regressor2.fit(X1_train,y1_train)
with open("one_year_pred_model_two.pkl","wb") as file:
    pickle.dump(regressor2,file)

In [15]:
y1_pred_svr=regressor2.predict(X1_test)


In [16]:
from sklearn.metrics import r2_score
r2_score(y1_test,y1_pred_svr)


0.8261957234331605