In [7]:
import numpy as np
import pandas as pd
import pickle

In [2]:
dataset = pd.read_csv('The_Grades_Dataset.csv')
for column in dataset:
    dataset[column]=dataset[column].replace('A+',4.0)
    dataset[column]=dataset[column].replace('A',4.0)
    dataset[column]=dataset[column].replace('A-',3.7)
    dataset[column]=dataset[column].replace('B+',3.3)
    dataset[column]=dataset[column].replace('B',3.0)
    dataset[column]=dataset[column].replace('B-',2.7)
    dataset[column]=dataset[column].replace('C+',2.3)
    dataset[column]=dataset[column].replace('C',2.0)
    dataset[column]=dataset[column].replace('C-',1.7)
    dataset[column]=dataset[column].replace('D+',1.3)
    dataset[column]=dataset[column].replace('D',1.0)
    dataset[column]=dataset[column].replace('D-',0.7)
    dataset[column]=dataset[column].replace('WU',0)
    dataset[column]=dataset[column].replace('W',0)
    dataset[column]=dataset[column].replace('F',0)
    dataset[column]=dataset[column].replace('I',0)

In [3]:

X2 = dataset.iloc[:, 1:23].values
y2 = dataset.iloc[:, -1].values

In [4]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer.fit(X2[:,1:23])
X2[:,1:23]=imputer.transform(X2[:,1:23])
print(X2[1:23])

[[4.  1.  1.3 1.  2.7 2.  1.  4.  1.3 1.  3.3 2.3 2.7 1.7 1.3 1.3 1.  2.
  1.  2.7 2.  1. ]
 [4.  3.  4.  2.7 3.3 4.  2.7 3.3 3.7 3.7 2.7 3.7 4.  4.  4.  4.  4.  4.
  3.7 4.  3.7 4. ]
 [1.  2.3 1.3 1.  1.  3.7 1.3 1.7 1.  2.3 1.  3.  1.3 2.7 1.  2.  3.3 2.3
  1.  1.3 1.  1. ]
 [3.7 3.7 3.7 3.3 4.  4.  3.7 3.3 4.  3.7 2.  4.  4.  3.7 3.7 3.7 2.7 4.
  3.7 4.  3.7 3.7]
 [4.  2.7 3.  1.3 2.3 3.7 2.3 3.  3.3 3.3 1.7 3.7 2.7 3.3 3.7 3.3 3.  3.7
  3.  3.7 3.7 2.3]
 [2.7 1.7 3.7 1.  3.7 3.  4.  3.3 3.7 3.3 3.7 4.  2.  2.3 1.7 2.7 2.7 3.3
  2.  4.  2.3 1.7]
 [3.3 3.3 2.3 2.  2.  3.7 1.7 3.7 3.  3.7 3.3 4.  3.3 3.3 2.  3.7 3.3 3.7
  2.  3.7 2.3 2. ]
 [3.7 2.  3.7 1.3 3.  3.7 3.7 3.7 3.3 3.7 3.7 4.  4.  3.7 2.7 3.7 3.7 4.
  2.7 4.  2.3 2.3]
 [4.  3.  2.3 3.  3.  3.7 2.  2.7 3.7 4.  2.3 3.7 2.7 4.  3.7 4.  2.7 4.
  2.7 3.7 2.7 3.7]
 [3.7 2.7 3.3 1.7 1.7 2.7 2.3 2.7 4.  3.7 1.3 4.  2.7 3.7 1.  3.3 2.7 3.
  2.3 3.7 1.3 2. ]
 [3.7 2.  3.7 2.3 1.7 4.  2.7 3.3 3.7 3.7 3.7 4.  3.3 3.7 3.7 4.  3.7 4.
  4

In [5]:
from sklearn.model_selection import train_test_split
X2_train,X2_test,y2_train,y2_test=train_test_split(X2,y2,test_size=0.1,random_state=0)
print(X2_train)

[[4.  2.3 3.7 ... 2.7 2.7 1.7]
 [2.3 1.3 3.  ... 3.3 3.3 2.3]
 [3.3 2.  4.  ... 3.  3.7 2.7]
 ...
 [3.7 3.7 4.  ... 4.  3.7 3.7]
 [4.  4.  4.  ... 3.7 4.  4. ]
 [3.7 2.3 4.  ... 2.7 3.3 4. ]]


training model 2 on linear regression

In [8]:
from sklearn.linear_model import LinearRegression
regressor1 = LinearRegression()
regressor1.fit(X2_train, y2_train)
with open("two_year_pred_model_one.pkl","wb") as file:
    pickle.dump(regressor1,file)

In [9]:
y_pred_linear = regressor1.predict(X2_test)

In [10]:
from sklearn.metrics import r2_score
r2_score(y2_test,y_pred_linear)

0.9130113829812101

In [11]:
from sklearn.ensemble import RandomForestRegressor
regressor2 = RandomForestRegressor(n_estimators=20,random_state=0)
regressor2.fit(X2_train, y2_train)
with open("two_year_pred_model_two.pkl","wb") as file:
    pickle.dump(regressor2,file)

In [12]:
y_pred_rfr=regressor2.predict(X2_test)

In [13]:
from sklearn.metrics import r2_score
r2_score(y2_test,y_pred_rfr)

0.9315948122387205